revert(*): revert resource-group, storage-account, appservice-windows and keyvault changes
Nmbrs/tf-modules pull request #46
Opened 2022-02-28 19:14 UTC by filipefigueredo

# Description

The goal of this PR is to revert unintended changes in the  following modules:
- keyvault
- app-service-windows
- resource-group
- storage-account

# Motivation and Context

At the  PR #39, I had my code base outdated and merged old stuff from main branch that changed behaviors previously updated.

# How Has This Been Tested?

Please compare the reverted changes with the commit `952ead1`
# Screenshots

# Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

# Checklist:

- [ ] My code has security implications.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2022-02-28 20:35 UTC, fargozhu commented on azure/storage_account/data.tf
> +}
[recommendation] I would move the data block to the main file instead, so we can easily follow the flow in one place only.

2022-02-28 20:42 UTC, fargozhu approved these changes
All comments and suggests are nice to have, but I am still concerned with the storage account module and the fact that is getting the location value from the resource group data block.

2022-02-28 20:42 UTC, fargozhu commented on azure/storage_account/main.tf
> +resource "random_id" "storage_account_name" {
```suggestion
data "azurerm_resource_group" "rg" {
  name = var.resource_group_name
}

resource "random_id" "storage_account_name" {
```

2022-02-28 20:42 UTC, fargozhu commented on azure/storage_account/main.tf
> +  min_tls_version           = var.min_tls_version
```suggestion
  min_tls_version           = var.min_tls_version
  
  tags = data.azurerm_resource_group.rg.tags
```

2022-02-28 21:05 UTC, fargozhu requested changes
Most are comments, but the missing tags on the storage account needs to be added.

2022-02-28 22:47 UTC, filipefigueredo commented
All the suggestions for storage account were implemented.

2022-03-01 08:23 UTC, fargozhu approved these changes

2022-03-01 09:08 UTC, merged