feature(keyvault): add environment variable to keyvault module
Nmbrs/tf-modules pull request #97
Opened 2022-04-06 19:45 UTC by filipefigueredo

## Description

The main goal of this PR is to include an environment variable to keyvault module instead of using the environment tag provided by the group. By doing sos, the environment provided in existing resource-groups tags will not affect the keyvault name.

## PR Checklist

Please ensure the following before submitting this PR:

- [X] You complied with the code style of this project.
- [X] You formatted all Terraform configuration files to a canonical format (Hint: `terraform fmt`).
- [X] You validated all Terraform configuration files (Hint: `terraform validate`).
- [X] You executed a speculative plan, showing what actions Terraform would take to apply the current configuration (Hint: `terraform plan`).
- [X] The documentation was updated (`README.md`, `CHANGELOG.md`, etc.).
- [ ] Whenever possible, the dependencies were updated to the latest compatible versions.

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix.
- [X] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no interface changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes.
- [ ] Other... Please describe:

### What is the new behavior?

- Add environment variable to keyvault module

### How to test it

1. At the root of the `tf-module` repository, create a `main.tf` file with the following code:`
```hcl
terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~> 2.65"
    }
  }

  required_version = ">= 1.0.0"
}

provider "azurerm" {
  features {
  }
}

module "resource-group" {
  source      = "./azure/resource-group"
  name        = "heimadall-demo"
  environment = "Dev"
  country     = "nl"
  squad       = "infra"
  product     = "internal"
  extra_tags = {
    Datadog = "Monitored"
  }
}

module "keyvault" {
  source              = "./azure/keyvault"
  name                = "Heimdall"
  environment         = "Dev"
  external_usage      = true
  resource_group_name = module.resource-group.name
  extra_tags = {
    Datadog = "Monitored"
  }
}
```
2. `terraform init`
3. `terraform validate`
4. `terraform plan` and check if the speculative plan seems ok (it should contain 5 modules: the `resource-group`, `caf` module for the resource-group, `keyvault`, keyvault's default policy and `caf` module for the keyvault,)
5. `terraform apply -auto-approve`
6. Check if the resource group is composed by `kv-nmbrs` prefix, the name `heimdall` and postfix `e-dev`
7. After finishing testing, please don't forget to destroy the resource: `terraform destroy -auto-apply`

### Does this PR introduce a breaking change?

- [ ] Yes.
- [X] No.

### Other information

2022-04-06 20:16 UTC, fargozhu requested changes
![Screenshot 2022-04-06 at 22 15 44](https://user-images.githubusercontent.com/904062/162063288-9d0e9cd2-a748-432c-a4a8-23704d3d3512.png)

2022-04-06 20:37 UTC, RuiEloiVisma approved these changes

2022-04-06 21:23 UTC, pmmluis approved these changes

2022-04-07 00:39 UTC, fargozhu approved these changes

2022-04-07 08:03 UTC, merged